# permissions for end users to edit coinworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: coinworkflow-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-operator-orchestration-example
    app.kubernetes.io/part-of: kubernetes-operator-orchestration-example
    app.kubernetes.io/managed-by: kustomize
  name: coinworkflow-editor-role
rules:
- apiGroups:
  - orchestration.example
  resources:
  - coinworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestration.example
  resources:
  - coinworkflows/status
  verbs:
  - get
